name: Deploy to VPS

on:
  push:
    branches:
      - master 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no shankar@82.25.101.68 << 'EOF'
            cd /home/shankar/Api
            git pull origin master
            npm install
            npm run build
            sudo /bin/systemctl restart my-api
          EOF
